#:schema node_modules/wrangler/config-schema.json
name = "example-hono-on-workers"
main = "src/index.ts"
compatibility_date = "2024-10-18"


[[d1_databases]]
binding = "DB"
database_name = "my-db"
database_id = "<Database-ID>"
preview_database_id = "<Database-ID>"
migrations_dir = ".drizzle-out"